### ISSUE TITLE
Sergio Proyecto w3 database

### ISSUE THREAD

**Issue by SergioSuarezgh** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#1]
https://github.com/SergioSuarezgh/sql-data-base-building.git

**Comment by AdrianCiges** [comment]
Algunos detalles:
-El readme queda muy tosco. Usa algunos emojis o imágenes y evita poner código. 
-En la limpieza has dejado algunos errores impresos. Ojo 👀
-Tienes un archivo _init_ py vacío. Why?
-El .head() en el archivo de limpieza porfa!
-En la limpieza el archivo está incompleto, no?
Échale un ojo y remata el trabajo!
