### ISSUE TITLE
[w3-database-project] Julia Sabatel

### ISSUE THREAD

**Issue by juliasabatel** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#10]
https://github.com/juliasabatel/SQL_database_building_Proyecto.git

**Comment by AdrianCiges** [comment]
Muy bien el readme, aunque echo en falta algún emoji (gusto personal tal vez) y la imagen de cabecera no pondría la de MySQL sino algo que describa tu proyecto, algo más divertido, PERO: ¿Dónde está el código? Has olvidado subir el notebook y el archivo sql (o txt) con las queries! Arregla eso y avísanos

**Comment by AdrianCiges** [comment]
Nice! Buen trabajo de limpieza, cuidado que te has dejado un error impreso en el código (queda feo) cuando intentaste la conexión con SQL workbench. Has usado lamba 👀, está genial pero ojo con usar código que te pueda costar entender en un futuro si retomas el proyecto (como consejo general, este proyecto no creo que no retomes, o sí).
Echo en falta una carpeta "src" para el código. Has usado una para queries, pero lo suyo es que el notebook y los archivos sql o txt con queries los metas en "src". 
Las queries y las relaciones guay. Sigue así.
