### ISSUE TITLE
[ w3-database-project] Arianne Murillo

### ISSUE THREAD

**Issue by Arimugon** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#11]
https://github.com/Arimugon/Proyecto_Movies_SQL.git

**Comment by OrianAmpuero** [comment]
Muy bien Ari, se nota el curro y has logrado dar con la old hdd como es, igual sería bueno pnerle otro nombre para que tenga sentido con lo que contiene la tabla. como oportunidades de mejora te comento:
-en el readme trata de no poner códigos y de hacerlo mas llamativo para el lector, ya que eso te ayudara en un futuro con los recruiters 
-las carpetas principales suelen ser: data(csv limpios), src(funciones, jupyter con limpieza...), img(imágenes relacionadas con el repo..)  aunque sé que has tenido problemas con el gitignore trata de mejorar esos detalles y tener al día los repos de los proyectos

Ánimo que sé que puedes con esto y más!! :)
