### ISSUE TITLE
[W3-database-project] Víctor

### ISSUE THREAD

**Issue by victorrmtz** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#13]
https://github.com/victorrmtz/Proyecto-SQL.git

**Comment by AdrianCiges** [comment]
Buen trabajo, te comento detalles:
-Has organizado bien el repo por carpetas, pero te ha faltado una (src) para el código (archivos ipynb, sql...)
-El readme guay, con los detalles que ya te comenté, y muy interesante el extra que has añadido.
-Las relaciones perfect, con el bonus de las tablas que has creado. Top.
Sigue así!
