### ISSUE TITLE
[w3-database-project] Jaime Manrique

### ISSUE THREAD

**Issue by Jaimemanrique** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#15]
https://github.com/Jaimemanrique/semana_3_sql.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Jaime!! se ve la evolución y el curro detrás del proyecto, sigue así...
En cuanto al readme, busca un tiempo para mejorarlo porque vale la pena, trata de tener en el repo solo los csv limpios en la carpeta llamada data  y todos los archivos en carpetas

:)
