### ISSUE TITLE
[w3-database-project] David Tejedor

### ISSUE THREAD

**Issue by Davidteje** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#16]
https://github.com/Davidteje/w3-database-project.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo David! Se nota la mejoría y el curro que hay en el proyecto. 
Como oportunidades me mejora te cuento:
-la tabla de old hdd debería quedarse únicamente con los id que son los que proporcionan toda la info de esas tablas y el nombre también sería buen cambiar para que tenga mayor relación. 
-En el repo solo quédate solo con los csv limpios en la carpeta data.
