### ISSUE TITLE
[w3-database-project] Jaime Muñoz 

### ISSUE THREAD

**Issue by JIMYTHEONE** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#17]
https://github.com/JIMYTHEONE/sql-data-base-building.git

**Comment by AdrianCiges** [comment]
Se ve el curro pero honestamente necesitas mejorar ese repo sí o sí. Escribe un readme que explique tu trabajo, organiza los archivos en carpetas como data (para archivos de datos), src (para archivos de cógido), img (para imágenes)... Dale caña!!!
