### ISSUE TITLE
[ w3-database-project] "xabier garcia"

### ISSUE THREAD

**Issue by XabierGarciaMartins** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#18]
https://github.com/XabierGarciaMartins/w3-database-project.git

**Comment by XabierGarciaMartins** [comment]
https://github.com/XabierGarciaMartins/w3-database-project.git

**Comment by AdrianCiges** [comment]
Te comento cositas:
-El readme cuídalo, es la primera impresión que se lleva quien entre a tu repo a ver tu trabajo.
-Has subido el archivo de contraseñas. Debías haber puesto en el gitignore su nombre para que no te lo subiera, sino cualquiera puede ver tu contraseña.
-Has usado una carpeta (data) para los archivos, haz lo mismo para el resto: src para código, img para imágenes, etc.
