### ISSUE TITLE
[w3-database-project] Aaron Nebreda

### ISSUE THREAD

**Issue by AaronNebreda** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#19]

**Comment by AaronNebreda** [comment]
https://github.com/AaronNebreda/Building_mySQL_DataBase

**Comment by OrianAmpuero** [comment]
Muy bien trabajado el proyecto, como oportunidades de mejora te diría que trataras de poner el readme mas resumido en cuanto a las queries que no se vean todas las capturas, buscaría la forma de explicarlas pero sin mostrar código y la tabla de old hdd como consejo pondría otro nombre que vaya acorde con lo que significa esa tabla y yo hubiese dejado el id category porque ya estaba relacionado así.. Por lo demás muy bien y sigue así

**Comment by OrianAmpuero** [comment]
Alejandro! Muy bien en la presentación, se nota el esfuerzo y te animo a seguir así... Como oportunidades de mejora:
-solo dejar en la tabla old hdd los id para mejor visibilidad y como consejo cambiar el nombre para que tenga significativo 
-en la exposición, mirar mas a tus compañeros y no tanto a la pantalla, así conectas más y captas la atención.. Trata de no mencionar los problemas porque nadie lo sabe y quedarte con lo bueno de tu trabajo que ya es bastante :)
- en el repo, la carpeta data dejar los csv limpios únicamente
