### ISSUE TITLE
[w3-database-project] Pablo Garcia Berdoy

### ISSUE THREAD

**Issue by pgb314** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#2]
https://github.com/pgb314/w3-database-project.git

**Comment by AdrianCiges** [comment]
El archivo de queries mételo en src.
El readme está bien pero retócalo, queda aburrido y doficil de ver como se organiza. Está todo muy seguido. 
Las relaciones están perfectas.
En la limpieza no te has calentado mucho, no era el objetivo principal del ejercicio, pero no lo dejes correr!
Buen trabajo en general!
