### ISSUE TITLE
[ w3-database-project] Iñigo Larrea

### ISSUE THREAD

**Issue by pombo7676** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#20]
https://github.com/pombo7676/w3-database-project.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Iñigo! Mejorando en los proyectos y te animo a seguir así... Como oportunidades de mejora:
-en la presentación trata de no cerrar los brazos para mostrarte mas abierto a tus compis
-trata de no mostrar el código, ya que en un futuro será tu portfolio y no todos los recruiters entenderán eso
-muy bien la tabla de old_hdd, pero para que tenga mas sentido luego le puedes cambiar el titulo como por ejemplo (film_actor)
