### ISSUE TITLE
[ w3-database-project] Alicia Hernansanz

### ISSUE THREAD

**Issue by aliciahernansanz** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#21]
https://github.com/aliciahernansanz/w3-database-project

**Comment by OrianAmpuero** [comment]
Muy bien Alicia! Te animo a ponerte creativa con los readme y hacerlo llamativo al lector ;) un reto que sé que puedes con ello. Por lo demás bien, la tabla de old hdd lograda; me hizo falta una querie pero espero que se te haya pasado subirla :) jaja...
