### ISSUE TITLE
[w3-database-project] David Cuenca

### ISSUE THREAD

**Issue by kuenk** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#23]
https://github.com/kuenk/sql-data-base-building

**Comment by OrianAmpuero** [comment]
Bien David!! como consejo trata de organizar mejor el repo con sus carpetas que eso mola :) y en el caso de los cvs solo deja los limpios. las relaciones de la base de datos hay que revisarlas mejor (la  tabla actor quedo sola y la de old hdd no esta como debería pero te animo a trabajar en ello

**Comment by kuenk** [comment]
Hola Oriana.

Soy consciente de ello. Con el cambio del portátil perdí algunas cosas que
no había guardado aún (lección aprendida)

Gracias
