### ISSUE TITLE
Silvia Barge

### ISSUE THREAD

**Issue by Barge7** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#25]
https://github.com/Barge7/Proyecto-SQL

**Comment by AdrianCiges** [comment]
Guay el readme, pero echo en falta algun emoji y cuidado con la dimensión de los títulos. Los de las tablas son más grandes que el de la sección de los contiene. 
Las relaciones perfect, pero por ser detallista, cuidado que en la captura de pantalla tienes una de las tablas seleccionadas y salen los cuadraditos blancos de los márgenes y queda feo 👀
Los archivos de código mételos en una carpeta src, no en data.
La limpeiza guay y has lanzado queries desde jupyter, nice!
Buen trabajo!
