### ISSUE TITLE
[w3-database-project] Pablo Galán

### ISSUE THREAD

**Issue by pablogalann** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#5]
https://github.com/pablogalann/w3-database-project

**Comment by AdrianCiges** [comment]
El readme una maravilla, pero evita poner código en él. Como gusto personal, echo en falta algún emoji, pero has usado muchas imágenes así que no se hace aburrido, muy bien.
Las relaciones están perfect, pero en la parte de las queries es mejor que pongas las tablas resultantes que las queries en sí. 
Muy bien organizado el repo, pero my_code llámalo "src" por convención. 
En la limpieza eliminaste 'release_year' de film pero no de "old_hdd", why? 👀
Muy buen trabajo en general!
