### ISSUE TITLE
[w3-database-project] Rocío Moreno

### ISSUE THREAD

**Issue by rciomoreno** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#6]
https://github.com/rciomoreno/Proyecto_2.git

**Comment by AdrianCiges** [comment]
Buen trabajo. Algunos detalles:
-No olvides el .head() que algunas tablas las has dejado impresas y vuelve a dolerme el dedito que hacer scroll ☝️😭
-El readme está bien, pero evita poner código.
-El repo organízalo el carpetas. img para imagenes, src para código, data para archivos de datos...
-Como consejo, renombra las capturas de pantalla antes de subirlas, que queda feo el nombre entero de "Captura de pantalla..."
-La limpieza guay y las relaciones perfect. Queries good pero te faltan unas cuantas. 
Keep going :)
