### ISSUE TITLE
[w3-database-project]Arturo

### ISSUE THREAD

**Issue by Artturoo** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#7]
https://github.com/Artturoo/DATABASE_PROJECT.git

**Comment by OrianAmpuero** [comment]
Muy bien Arturo, se nota el curro y has ido avanzando poco a poco, sigue así que vas bien :) en cuanto a oportunidades de mejora:
-trata de tener los brazos abiertos y no dar la espalda a tus compis; sé que hay nervios pero tranquilo que es parte del proceso. 
-(exportación y visualización) lo aprendido esta semana son las bases de datos relacionales en SQL, queries, ERD y cargas de base de datos de python a interfaz gráfica como por ejemplo workbench...
-Mejorar el readme para que sea más llamativo (imágenes o iconos..)
