### ISSUE TITLE
[w3-database-project] Ana Chaparro

### ISSUE THREAD

**Issue by AnaChaparro** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#8]
https://github.com/AnaChaparro/Project-Movies-DB.git

**Comment by OrianAmpuero** [comment]
Muy bien trabajado Ana! como oportunidades de mejora te diría que en el readme manejes las queries diferentes para no tener todas esas capturas (puedes explicar que búsquedas querías sacar y ya al que le interese que entre en las carpetas a ver los códigos y los resultados) y en la tabla old hdd como consejo cambiaría de nombre para que se entienda de que va (film_actor o algo así)
