### ISSUE TITLE
[w3-database-project] Alejandro Hornero

### ISSUE THREAD

**Issue by Baker-man** [Ironhack-Data-Madrid-Octubre-2022/w3-database-project#9]
https://github.com/Baker-man/sql-data-base-building.git

**Comment by OrianAmpuero** [comment]
Alejandro! Muy bien en la presentación, se nota el esfuerzo y te animo a seguir así... Como oportunidades de mejora:
-solo dejar en la tabla old hdd los id para mejor visibilidad y como consejo cambiar el nombre para que tenga significativo
-en la exposición, mirar mas a tus compañeros y no tanto a la pantalla, así conectas más y captas la atención.. Trata de no mencionar los problemas porque nadie lo sabe y quedarte con lo bueno de tu trabajo que ya es bastante :)
-en el repo, la carpeta data dejar los csv limpios únicamente
